name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
    #- if: ${{ success() }}
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.ROOT_ADRESS }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
      with:  
        source: "."
        target: "/var/www/foo"
    #- if: ${{ success() }}
    - name: executing a remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ROOT_ADRESS }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        key: ${{ secrets.SSH_KEY}}
        port: ${{ secrets.PORT }}
        script: | 
          whoami
          ls -l
